// Large pool of real company names to probe against every supported ATS
// (Greenhouse, Lever, Ashby, Workable). This is a scanning universe, not a
// guarantee - megaVerify.js tests slug variants of each name against the
// real APIs and keeps only what actually resolves to a live job board.
module.exports = [
  // Big tech / global product
  "Google","Microsoft","Amazon","Meta","Apple","Netflix","Adobe","Salesforce","SAP","Oracle","IBM","Coupang",
  "Intel","Nvidia","Qualcomm","Cisco","VMware","Dell","HP","HPE","Walmart","Target","Goldman Sachs",
  "JPMorgan","Morgan Stanley","American Express","Visa","Mastercard","PayPal","Uber","Lyft","Booking",
  "Expedia","Airbnb","ServiceNow","Workday","Atlassian","Autodesk","Synopsys","Cadence","Arm","AMD",
  "Texas Instruments","Analog Devices","Micron","Western Digital","Seagate","NetApp","Nutanix",
  "Juniper Networks","Broadcom","Honeywell","Siemens","Bosch","Philips","Nokia","Ericsson","Samsung",
  "LG","Sony","Continental","Harman","MathWorks","Citrix","Red Hat","SUSE","Pure Storage","Rubrik",
  "Cohesity","Commvault","CrowdStrike","Palo Alto Networks","Fortinet","Check Point","F5","Akamai",
  "Cloudflare","Twilio","Zendesk","HubSpot","Freshworks","Zoho","ThoughtWorks","Epam","Globant","DXC",
  "NTT Data","GlobalLogic","Publicis Sapient","Amdocs","Nagarro","Endava","Virtusa","Mindtree","Wipro",
  "Infosys","TCS","HCLTech","Tech Mahindra","Cognizant","Capgemini","Accenture","LTIMindtree","Mphasis",
  "Persistent Systems","Hexaware","Coforge","Zensar","Birlasoft","Cyient","KPIT","Sonata Software",
  "Happiest Minds","Newgen Software","Ramco Systems","Intellect Design Arena","Nucleus Software","Subex",
  // Fintech / banking
  "Deutsche Bank","Barclays","HSBC","Standard Chartered","Citi","Bank of America","Wells Fargo","UBS",
  "BNY Mellon","State Street","Northern Trust","Nomura","Macquarie","Societe Generale","BNP Paribas",
  "Fidelity","Fiserv","FIS","Synchrony","Moodys","S&P Global","LSEG","Bloomberg","Two Sigma","Jane Street",
  "Optiver","Tower Research","DE Shaw","Capital One","Discover","Ally Financial","USAA","Charles Schwab",
  "BlackRock","Vanguard","Invesco","Franklin Templeton","MSCI","Nasdaq",
  // Indian unicorns / startups
  "Flipkart","Swiggy","Zomato","Ola","Paytm","PhonePe","CRED","Razorpay","Meesho","Udaan","BYJUS",
  "Unacademy","Vedantu","upGrad","Cult.fit","Curefit","Dunzo","BigBasket","Blinkit","Nykaa","Lenskart",
  "Urban Company","MakeMyTrip","Yatra","Cleartrip","PolicyBazaar","ACKO","Digit Insurance","Groww",
  "Zerodha","Upstox","Angel One","INDmoney","Slice","Jupiter","Fi Money","Navi","ShareChat","Dailyhunt",
  "InMobi","MoEngage","CleverTap","Chargebee","Postman","BrowserStack","Hasura","Darwinbox","Whatfix",
  "Icertis","Druva","Zenoti","Innovaccer","Amagi","Yellow.ai","Observe.AI","Uniphore","Locus","Shiprocket",
  "Delhivery","Ecom Express","Xpressbees","Porter","Rapido","Ather Energy","Ola Electric","Zepto",
  "Country Delight","Licious","Khatabook","OkCredit","Vyapar","Simpl","LazyPay","Kissht","MoneyView",
  "Cashfree","Juspay","Pine Labs","BharatPe","Open Financial","Zeta","Yulu","Blusmart","Zoomcar","Spinny",
  "CarDekho","CARS24","Droom","Housing","NoBroker","99acres","Naukri","Justdial","IndiaMART","Netmeds",
  "PharmEasy","1mg","Practo","Apollo247","Curefoods","Rebel Foods","Games24x7","Dream11","MPL","Nazara",
  "WinZO","My11Circle","Rippling","Deel","Gusto","Checkr","Samsara","Scale AI","Anthropic","OpenAI",
  "Perplexity","Cloudera","Teradata","Informatica","MuleSoft","Workato","Zapier","Fastly","Vercel",
  "Netlify","DigitalOcean","Linode","Rackspace","Equinix","Flexport","Convoy","Instacart","DoorDash",
  "Grubhub","Yelp","Eventbrite","TripAdvisor","Trivago","Kayak","Wayfair","Etsy","eBay","Shopify",
  "BigCommerce","Squarespace","GoDaddy","Wix","Automattic",
  // SaaS / dev tools / cloud
  "Confluent","Elastic","MongoDB","Snowflake","Databricks","Datadog","New Relic","Splunk","GitLab",
  "GitHub","Docker","HashiCorp","JFrog","Sumo Logic","PagerDuty","Grafana Labs","Snyk","Tenable",
  "Rapid7","Qualys","Zscaler","Okta","Auth0","CyberArk","Varonis","Imperva","Arista Networks",
  "Extreme Networks","Riverbed","Vonage","Genesys","Five9","Talkdesk","Sprinklr","Highspot","Gainsight",
  "Clari","Outreach","Gong","ZoomInfo","6sense","Drift","Front","Help Scout","Kustomer","Amplitude",
  "Mixpanel","Segment","Braze","Iterable","Klaviyo","Notion","Figma","Canva","Miro","Airtable","Monday",
  "ClickUp","Asana","Smartsheet","Zoom","Slack","Dropbox","Box","DocuSign","Calendly","Webflow",
  "Typeform","Grammarly","Duolingo","Coursera","Udemy","Chegg","Quizlet","Khan Academy","Discord",
  "Reddit","Pinterest","Snap","Spotify","SoundCloud","Coinbase","Kraken","Circle","Robinhood","Affirm",
  "Chime","Brex","Plaid","Stripe","Ramp","Mercury","Retool","Vanta","Faire","Vercel","Linear","Attentive",
  "Watershed","Pave","Hex","Census","Runway","Vendr","Hightouch","Metronome","Cresta","Posthog","Supabase",
  "Temporal","Warp","Replit","Modal","Browserbase","Cognition","Sierra","Harvey","Glean","Writer","Clay",
  "Gamma","Coda","Airbyte","Dagster","Prefect","Astronomer","Y Combinator","Scale","Anduril","SpaceX",
  "Palantir","Snowflake Computing","Confluent Inc",
  // Enterprise / MNC GCCs
  "Yahoo","Verizon","AT&T","T-Mobile","Comcast","Charter","Dish Network","SiriusXM","Warner Bros Discovery",
  "NBCUniversal","Paramount","Roku","Fitbit","Garmin","GoPro","Logitech","Western Union","MoneyGram",
  "Ripple","Chainalysis","Gemini","Bitpanda","Revolut","Wise","Klarna","Adyen","Block","Toast","Upwork",
  "Fiverr","LinkedIn","Indeed","Glassdoor","ZipRecruiter","Monster","CareerBuilder","Genpact","WNS",
  "EXL Service","Firstsource","Concentrix","TTEC","Teleperformance","Conduent","Gartner","Forrester",
  "Nielsen","Kantar","Booz Allen Hamilton","Leidos","SAIC","Northrop Grumman","Lockheed Martin","Boeing",
  "Airbus","Collins Aerospace","General Electric","3M","Emerson Electric","Schneider Electric","ABB",
  "Rockwell Automation","Eaton","Johnson Controls","Trane Technologies","Danaher","Thermo Fisher",
  "Agilent","Corning","DuPont","Dow","BASF","ExxonMobil","Shell","Chevron","Cummins","Whirlpool",
  "Electrolux","Havells","Voltas","Marvell","Skyworks","Renesas","NXP","Infineon","STMicroelectronics",
  "ON Semiconductor","MediaTek","Lattice Semiconductor","KLA","Applied Materials","Lam Research","ASML",
  "GlobalFoundries","Reliance Jio","Bharti Airtel","Vodafone Idea","Ciena","Delphi","Visteon","ZF Group",
  "Mahindra","Tata Motors","Maruti Suzuki","Hyundai","Ashok Leyland","Bajaj Auto","TVS Motor",
  "Royal Enfield","GE Healthcare","Optum","Cerner","Cigna","Eli Lilly","Pfizer","Novartis","Merck",
  "AstraZeneca","Sanofi","Roche","Abbott","Medtronic","Baxter","Disney Hotstar","Sony Pictures Networks",
  "Zee Entertainment","Electronic Arts","Zynga","King","Ubisoft",
  // AI / ML startups (heavy Greenhouse/Ashby adopters)
  "Mistral AI","Cohere","Adept","Inflection AI","Character AI","Stability AI","Midjourney","Runway ML",
  "ElevenLabs","Synthesia","Hugging Face","Weights and Biases","Together AI","Groq","Cerebras","SambaNova",
  "Lambda Labs","CoreWeave","Anyscale","Pinecone","Weaviate","Qdrant","LangChain","LlamaIndex","Tavus",
  "Speak","Sana Labs","Tome","Otter.ai","Fireflies.ai","Krisp","Descript","Suno","Udio","Luma AI","Pika",
  "World Labs","Physical Intelligence","Figure AI","Skild AI","1X Technologies","Covariant","Waabi",
  // Crypto / web3
  "Uniswap","OpenSea","Consensys","Alchemy","Chainlink Labs","Dune Analytics","Messari","Blockdaemon",
  "Fireblocks","Anchorage Digital","BitGo","Ledger","Trust Wallet","MetaMask","Polygon","Solana Labs",
  "Avalanche","Aptos Labs","Sui Foundation","Worldcoin","Celestia","EigenLayer",
  // More US/EU startups
  "Zip","Rho","Ramp Business","Brex Inc","Navan","TripActions","Deputy","When I Work","Homebase",
  "Gusto Inc","Justworks Inc","Sequoia Consulting","Papaya Global","Remote.com","Oyster HR","Multiplier",
  "Velocity Global","Globalization Partners","Lattice","15Five","Culture Amp","Bonusly","Bucketlist",
  "Motivosity","Reflektive","Betterworks","Perdoo","Ally.io","Workboard","Productboard","Aha!",
  "Roadmunk","Craft.io","Airfocus","Miro Inc","FigJam","Whimsical","Lucidchart","Diagrams.net",
  "Framer","Spline","Rive","Principle","ProtoPie","InVision","Marvel App","Zeplin","Abstract",
  "Chromatic","Percy","Applitools","BrowserStack Inc","LambdaTest","Testim","Mabl","Functionize",
  "Katalon","Sauce Labs","CrossBrowserTesting","Ghost Inspector","Cypress.io","Playwright Inc",
  "Postman Inc","Insomnia","Hoppscotch","Swagger","Stoplight","Kong Inc","Tyk","Apigee","3Scale",
  "Gravitee","WSO2","Boomi","Celigo","Tray.io","n8n.io","Make (Integromat)","Pipedream","Automate.io",
  "Parabola","Hevo Data","Airbyte Inc","Fivetran Inc","Matillion","Talend Inc","Stitch Data",
  "Segment Inc","Rudderstack","mParticle","Amplitude Inc","Heap Inc","FullStory Inc","LogRocket",
  "Smartlook","Hotjar","Crazy Egg","Mouseflow","VWO","Optimizely","AB Tasty","Split.io","LaunchDarkly Inc",
  "Statsig","Eppo","GrowthBook","Flagsmith","ConfigCat","Unleash",
  // India: additional startups / D2C / soonicorns
  "Mamaearth","boAt","Wow Skin Science","Sugar Cosmetics","Purplle","Nykaa Fashion","Zivame","Bewakoof",
  "Snitch","The Souled Store","Fabindia","Cult Sport","HealthifyMe","Cure.fit Health","MFine","DocsApp",
  "Portea","1mg Technologies","Medlife","Truemeds","Pharmeasy Health","CarWale","BikeWale","Zigwheels",
  "Acko General Insurance","Turtlemint","RenewBuy","InsuranceDekho","Coverfox","Policybazaar Insurance",
  "BankBazaar","Paisabazaar","MyLoanCare","Rupeek Fintech","IndiaLends","EarlySalary","KreditBee",
  "Fibe","MoneyTap","CASHe","Freo","StashFin","mPokket","Bueno Finance","Jar App","Gullak","Multipl",
  "Vested Finance","Smallcase","Tickertape","StockEdge","Sensibull","Streak","Dhan","Fyers","Kite Zerodha",
  "Upstox Securities","5paisa","IIFL Securities","Motilal Oswal","Kotak Securities","HDFC Securities",
  "ICICI Direct","Angel Broking","Sharekhan","Groww Invest","ETMoney","Kuvera","INDwealth",
  "Meesho Commerce","GlowRoad","Shop101","DealShare","CityMall","Bazaar","Udaan Commerce","Jumbotail",
  "ElasticRun","Ninjacart","WayCool Foods","DeHaat","AgroStar","BigHaat","Farmart","Waycool",
  "Rebel Foods Kitchens","Faasos","Behrouz Biryani","Oven Story","Box8","Freshmenu","Chef Talk",
  "Swiggy Genie","Dunzo Merchant","Grab India","Gojek India","Bounce Bikes","Vogo","Yulu Bikes",
  "Ather Grid","Simple Energy","Bounce Infinity","Ola S1","Revolt Motors","Okinawa Autotech",
  "Hero Electric","BGauss","River Mobility","Euler Motors","Log9 Materials","Exponent Energy",
  "Ultraviolette","Matter Motor Works","Battery Smart","Sun Mobility","Chargepoint India","Statiq",
  // India: enterprise SaaS / dev tools
  "Zoho Corp","Freshdesk India","Kissflow","Zoho People","GreytHR","Keka HR","Zimyo","Factohr",
  "PeopleStrong","Springworks","Vantage Circle","Empuls","Xoxoday","Plum Benefits","Nivoda",
  "Whatfix Inc","Chameleon","Appcues","Pendo Inc","Userpilot","UserGuiding","Intercom Inc",
  "Freshchat","Freshservice","ManageEngine","Site24x7","Zoho Analytics","Zoho CRM","Zoho Books",
  "Wingify","VWO India","CleverTap Inc","MoEngage Inc","WebEngage","Netcore Cloud","Gupshup",
  "Kaleyra","Route Mobile","Karix Mobile","Exotel","Knowlarity","MyOperator","Ozonetel","Ameyo",
  "Freshdesk Contact Center","Servetel","Corefactors","LeadSquared","Kylas CRM","Salesmate",
  "Vtiger CRM","SalesBabu","Sell.do","Sellizer","Toolyt","Bizom","FieldAssist","Beat Route",
  "Locobuzz","SocialPilot","ContentStudio","Buffer India","Hootsuite India","Sprinklr India",
  // YC / global startups (batch 2)
  "Deel Inc","Vanta Inc","Rippling Inc","Merge","Finch","Codat","Plaid Inc","Unit","Synctera",
  "Column","Increase","Modern Treasury","Highnote","Marqeta","Galileo Financial","Bond Financial",
  "Treasury Prime","Alloy","Persona Inc","Middesk Inc","Sardine","Unit21","Hawk AI","ComplyAdvantage",
  "Chainalysis Inc","TRM Labs","Elliptic Inc","Solidus Labs","Lukka","Bitwave","TaxBit","CoinTracker",
  "Koinly","ZenLedger","Ledgible","Anchorage Digital Inc","Fireblocks Inc","Copper.co","Zodia Custody",
  "Komainu","METACO","Curv","Sepior","Unbound Security","Cybavo","BitGo Inc","Coinbase Custody",
  "Gemini Custody","Paxos","Circle Internet Financial","Tether","MakerDAO","Compound Labs","Aave",
  "dYdX","0x Labs","ConsenSys Software","Infura","Alchemy Inc","QuickNode","Moralis","Thirdweb",
  "Dune Analytics Inc","Nansen","Arkham Intelligence","Chainstack","Blockdaemon Inc","Figment Networks",
  "Kiln","Blockdaemon Networks","P2P.org","Staked","Bison Trails",
  // Robotics / hardware / space
  "Boston Dynamics","Agility Robotics","Berkshire Grey","Locus Robotics","6 River Systems","Fetch Robotics",
  "Zipline","Wing Aviation","Skydio","Shield AI","Anduril Industries","Rocket Lab","Relativity Space",
  "Firefly Aerospace","Astra Space","Planet Labs","Spire Global","BlackSky","Capella Space","Umbra Space",
  "Varda Space","Axiom Space","Sierra Space","ICON Technology","Redwood Materials","QuantumScape",
  "Solid Power","Form Energy","Commonwealth Fusion","Helion Energy","TAE Technologies","Zap Energy",
  // Climate / energy tech
  "Watershed Climate","Patch","Pachama","NCX","Sylvera","BeZero Carbon","South Pole","ClimateAi",
  "Arcadia Power","OhmConnect","Span.io","Electric Era","ChargePoint Inc","EVgo","Blink Charging",
  "Wallbox","ampUp","itselectric","Voltpost","Revel Transit","Zeta Energy","Sila Nanotechnologies",
  "Natron Energy","ESS Tech","Eos Energy",
  // EdTech
  "Byju's Learning","Toppr","Embibe","Simplilearn","Great Learning","upGrad Campus","Newton School",
  "Scaler Academy","Masai School","Pesto Tech","CodingNinjas","GeeksforGeeks","InterviewBit","AlgoExpert",
  "Codecademy","Pluralsight","LinkedIn Learning","Skillshare","MasterClass","Outschool","Age of Learning",
  "Renaissance Learning","IXL Learning","Newsela","Clever Inc","ClassDojo","Remind","Nearpod","Kahoot",
  "Quizizz","Edmentum","Instructure Canvas","D2L","Blackboard Inc","Anthology Inc","2U Inc",
  // HealthTech / BioTech
  "Innovaccer Health","Komodo Health","Truveta","Tempus Labs","Flatiron Health","Color Health","Ro Health",
  "Hims Hers","Cerebral","Talkspace","BetterHelp","Headspace Health","Calm.com","Noom","Whoop",
  "Oura Health","Levels Health","Function Health","Forward Health","One Medical","Carbon Health",
  "98point6","K Health","Sword Health","Hinge Health","Omada Health","Virta Health","Livongo",
  "Cityblock Health","Included Health","Maven Clinic","Nurx","Wheel Health","Devoted Health",
  "Clover Health","Bright Health","Oscar Health","Alignment Health","agilon health",
  // Real estate / PropTech
  "Opendoor","Offerpad","Compass Real Estate","Redfin","Zillow Group","Divvy Homes","Ribbon Home",
  "Better.com","Blend Labs","Roofstock","Fundrise","Cadre","VTS","Reonomy","HomeLight","Orchard",
  "Knock Homes","Doma","States Title","Nobul","Houwzer","Flyhomes","Side Inc","Real Brokerage",
  "eXp Realty","NoBroker Technologies","Housing Edge","PropTiger","Square Yards","Magicbricks",
  "CommonFloor","Grihapravesh","NestAway","Zolo Stays","Stanza Living","Colive","OYO Life",
  // Logistics / supply chain
  "Flexport Inc","Convoy Inc","Uber Freight","project44","FourKites","Samsara Inc","KeepTruckin",
  "Motive Technologies","Trucker Tools","Loadsmart","Transfix","Emerge","Freightos","Nuvocargo",
  "Zencargo","Sennder","Instafreight","Forto","Xeneta","Flexe","Stord","ShipBob","ShipHero",
  "Deliverr","Cin7","Extensiv","Shipwell","Turvo","Blume Global","Descartes Systems",
  // Gaming (more)
  "Roblox","Unity Technologies","Epic Games","Riot Games","Supercell","MiHoYo","NetEase Games",
  "Krafton","Garena","Sea Limited","MoonActive","Playtika","Scopely","AppLovin","Voodoo",
  "Rovio Entertainment","Niantic","Jam City","Machine Zone","Gameloft","Miniclip","Big Fish Games",
  "PlayStation Studios","Xbox Game Studios","Bungie","Insomniac Games","Naughty Dog","Respawn",
  // Media / streaming (more)
  "Peacock TV","Max (HBO)","Paramount Plus","Crunchyroll","YouTube","Twitch","Vimeo","Brightcove",
  "Kaltura","JW Player","Mux","Bitmovin","Wowza Media","Ooyala","Conviva","NPAW",
  // Insurance tech
  "Lemonade Insurance","Root Insurance","Hippo Insurance","Next Insurance","Coalition Inc","At-Bay",
  "Corvus Insurance","Vouch Insurance","Kin Insurance","Branch Insurance","Bestow","Ethos Life",
  "Ladder Life","Policygenius","Pie Insurance","Openly","Clearcover","Metromile",
  // Legal / HR / recruiting tech
  "Ironclad","Clio","LawGeex","Evisort","Spellbook","Harvey AI","Robin AI","Luminance","Kira Systems",
  "Greenhouse Software","Lever Inc","SmartRecruiters Inc","iCIMS","Jobvite","Bullhorn","Beamery",
  "Eightfold AI","HireVue","Pymetrics","Codility","HackerRank","CodeSignal","TestGorilla","Karat",
  "Interviewing.io","Triplebyte","Woven Teams","Qualified.io","DevSkiller","Vervoe",
  // Martech / adtech
  "The Trade Desk","Criteo","AppNexus","PubMatic","Magnite","Index Exchange","OpenX","Sharethrough",
  "InMobi Inc","AdColony","Vungle","IronSource","Chartboost","Tapjoy","Digital Turbine","Kochava",
  "AppsFlyer","Adjust","Branch Metrics","Singular","Tenjin","Kochava Inc",
  // More India: fintech / neo-banks / lending
  "Axio","Postpe","ePayLater","Twid","Setu","Signzy","Perfios","M2P Fintech","Zeta Suite",
  "Yubi (CredAvenue)","Vivriti Capital","Northern Arc Capital","Cred Avenue","Jocata","Karbon Card",
  "Enkash","Volopay","Happay","Zaggle","Niyo Global","Fi Federal","Jupiter Federal","Kotak 811",
  // More India: enterprise / B2B SaaS
  "Zoho Desk","Vymo","Leena AI","Haptik","Yellow Messenger","Verloop","Gupshup Inc","Freshworks Neo",
  "Springrole","Skillate","Talview","Mercer Mettl","AMCAT","iMocha","HireMee","Turing.com",
  "Turing Labs","Remotestar","Flexiple","Toptal India","Braintrust","Deel India",
];
